### ISSUE TITLE
Improve the code coverage reporting for developers

### ISSUE THREAD

**Issue by willingc** [systers/portal#113]
@ana-balica I did some more research on running coverage without exposing security tokens. [Codecov.io](http://codecov.io) may be a good solution. It is being used by [cookiecutter](https://github.com/audreyr/cookiecutter). There is a free version of codecov.io.

**Comment by ana-balica** [comment]
@willingc It might be an idea to use codecov versus coveralls. But travis will still show fail, because of the security keys. I don't know, but maybe it would be an idea to use an unencrypted SECRET_KEY env var (since this is the one causing the trouble). In production we have a totally different SECRET_KEY of course.
