### ISSUE TITLE
Users can access each other's information through urls

### ISSUE THREAD

**Issue by mish24** [systers/portal#197]
I would like to fix this issue.

**Comment by tonythomas01** [comment]
Please provide more information about the bug in your description. What URLs are affected, screenshots if any. 

Also, check out https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines for pointers.

**Comment by tonythomas01** [comment]
I think https://github.com/systers/portal/issues/177 is related. Probably there is a problem with how the user profile view is defined. The view should use a `CurrentUserMixin` which might be like: 

```
class CurrentUserMixin(object):
    model = User

    def get_object(self, *args, **kwargs):
        try: obj = super(CurrentUserMixin, self).get_object(*args, **kwargs)
        except AttributeError: obj = self.request.user
        return obj
```

and the view should go like: 
`class UserProfileView(LoginRequiredMixin, CurrentUserMixin, DetailView):` 

so that a user **CANNOT** view other user profiles in an edit profie view.

**Comment by tonythomas01** [comment]
@MeepyMay why are you closing these issues ? Are they fixed ?

**Comment by tapasweni-pathak** [comment]
We can have a discussion on this if we should go ahead with this feature and allow users to view each other's profile, memberships e.t.c. Not a bug but something to have a discussion on.

**Comment by tonythomas01** [comment]
@tapasweni-pathak Agreed. But that should've been mentioned before someone close this thing. Probably an issue over handling tickets on  Github - which do not support a workboard of tasks ... :/
