### ISSUE TITLE
Password change 

### ISSUE THREAD

**Issue by ninjakx** [systers/portal#231]
Should display the message  "The new password cannot be same as the old one" when new password and older password is same.

**Comment by nathalier** [comment]
Hi! I'll be happy to work on this.

**Comment by nathalier** [comment]
Hi! I'll be happy to work on this.

**Comment by nathalier** [comment]
Cannot find obvious way to resolve it..
Will appreciate any clues.

**Comment by sonakshisaxena1** [comment]
@tapasweni-pathak 
I am not able to find the name under which the old-passwords are hashed in our project. 
I was trying to resolve this issue, but got stuck in here. Can you please help?

**Comment by sonakshisaxena1** [comment]
@ninjakx @tapasweni-pathak 
I went through the code thoroughly and concluded that since we are using the already installed `allauth` package of django, so, we can't interfere with its behaviour to change the passwords. 
Therefore, we can't introduce this facility to check the new password with the old one.
Please do guide me if I am wrong.
