### ISSUE TITLE
Show previous page link while hovering on the back button on custom error pages

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/portal#233]

**Comment by sa7i** [comment]
![screenshot from 2017-10-17 23-17-12](https://user-images.githubusercontent.com/13400691/31680349-ab9d4e1c-b391-11e7-9596-3a5408433851.png)


Hey, I hacked up a quick solution using jquery and boostrap. Will this suit your needs?
I came from `/here-be-dragons`, by clicking the dummy link I made inside the page so cross site unset of `document.referrer` won't happen. This won't work if you're clicking on a link from an external page to this link due to security issues.

**Comment by tapasweni-pathak** [comment]
The link should be down left corner, how we see on a webpage when we hover over a link. Happy to have a pull request for this.

**Comment by sonakshisaxena1** [comment]
@tapasweni-pathak I tried to get the previous link on hovering over, and this is what I figured out-

If we add `onMouseOver="window.status='XYZ';` to `<a> tag` in our `custom pages` in `templates`, then we could get our desired text printed in the status bar on hovering over a link or in this case the **Back** button. 

But unfortunately, [`window.status`](https://www.w3schools.com/jsref/prop_win_status.asp) doesn't work on most of the browsers any longer. So, even though if we try this, we won't be able to make any changes to the current displayed link on the status bar.

I would be glad if you could guide me to some other solution, if there exists one.

**Comment by tapasweni-pathak** [comment]
Closed with 0d793c8c7637082fadf9981d0110f15f38bc72ab.
