### ISSUE TITLE
Feature - Add Linkedin Authentication

### ISSUE THREAD

**Issue by Jaemu** [systers/portal#345]
## Description
As a user,
I would like to be able to authenticate with my linkedin credentials,
so that I can have more options with which to authenticate.

## Documentation
https://developer.linkedin.com/docs/signin-with-linkedin

### Update [Required]
- [ ] Linkedin authentication integrated into the systers portal application
- [ ] LInkedin login badge added to sign up page

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[32] hours

**Comment by SETIADEEPANSHU** [comment]
I will like to work on this issue , as I have done similar work before . @Jaemu . Can I ?

**Comment by abhi20161997** [comment]
@Jaemu is someone working on this ? I would like to work on this.

**Comment by yatna** [comment]
Nice idea, but since this is a new feature, we may want to do this in GSoC phase.

**Comment by tapasweni-pathak** [comment]
Hey @yatna, got an email and looked at this notification, I would suggest not closing issue like this. This is needed currently in Portal. If you want to push it to some other release you could tag it with some label so that you can remember to come back to reopen it.

Also could be I'm not aware of completely why would it be better to close the issue.

cc @systers/portal @systers/admins.

**Comment by sa7i** [comment]
@yatna I agree with Tapasweni.
