### ISSUE TITLE
Meetup

### ISSUE THREAD

**Issue by rosariorobinson** [systers/portal#51]
In the requirements document, I didn't go into too much detail about this, but i'll add a req doc specifically for Meetup.

Currently, we use Meetup Everywhere for global meetups and it works fine for just disseminating information. However, each individual meetup community is not able to really promote any sponsors or information specific to them. They can comment, but that's about it.
http://www.meetup.com/systers/

What I would like to see is something like some of the following examples.
http://lesbianswhotech.org/events/
http://railsgirls.com/
http://www.pyladies.com/locations/

I want Systers to be able to easily organize a meetup locally or if they are traveling, see what meetups are happening in whatever city they're in at the time and be able to participate.  I'll design this out a bit more and maybe a conversation is warranted to discuss ideas on approach.

I want meetup control on our site like Lesbians Who Tech. The other two uses meetup.com. I think LWT uses eventbrite which I really like and there's lots of features with eventbrite. I think there are lots of features we can utilize with Eventbrite API for mobile, bar code, etc.

I'd like to start discussions here so we can collaborate on ideas.

**Comment by rosariorobinson** [comment]
I've completed the requirements document and added it to this repo. You can find the document at the link below.

https://github.com/systers/portal/tree/master/docs/requirements

**Comment by reachtarunhere** [comment]
Hi! @rosariorobinson I have gone through the requirments PDF file. The requirements listed for the system administrators can be met without much difficulty and I feel it will be a good idea to use a free Google Apps account for the mailing part (Point A).  

Regarding Meetup organizers if we maintain a central EventBrite account it should be possible to set the events its details etc. using their API (which I found to be pretty good and well documented). Also editing the details and uploading images for events should be possible.

There is one particular issue I am a bit skeptical about ie. approval of requests by organizers (point E) in case we keep the event listed on EventBrite and Open (invite only). Regarding the same I also checked out http://lesbianswhotech.org/events/ to get an idea of how their site is working. I found out that they are using the registration widget from EventBrite. As per my guess this does not provide them with control on the people who can register because after clicking register Event Brite allows entering any email id. Thus it makes it very difficult to track and allow only the users we want. The invite only option comes with its own issue (no access through the API) thus it has to be ruled out. I tried to dig around some solutions for this but only ended up with 
http://stackoverflow.com/questions/18946958/can-anything-be-done-to-limit-an-eventbrite-event-to-the-invited-individuals-onl 
http://stackoverflow.com/questions/10566137/how-register-ticket-for-some-event-from-eventbrite-api

Where according to both the links this is not possible and Event Brite does not plan to allow such API acess event in the future.

So except the control on who can register pretty much everything you mentioned shouldn't be too difficult to archive. I'll keep digging more and let you know if I find some solution. I am really excited about the portal and would love to contribute all I can.
