### ISSUE TITLE
Correct the Wiki link on the Navbar

### ISSUE THREAD

**Issue by sakshi1499** [systers/portal#573]
## Description
As a user,
I should be able to redirect to the correct wiki.

## Mocks
![image](https://user-images.githubusercontent.com/42520146/86624021-3d491280-bfe0-11ea-9809-399986bf1995.png)

### Update [Required]
- Redirect to the correct wiki link i.e. Current portal wiki link.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Neilblaze** [comment]
@sakshi1499 can you assign me this?

**Comment by SanketDG** [comment]
@Neilblaze There you go!

**Comment by sakshi1499** [comment]
@Neilblaze I hope this is your first time making a PR in Portal. This issue is strictly for first timers. If yes, yay go ahead ☺️

**Comment by Neilblaze** [comment]
Yes, this is the first time I'm making a PR in Portal.

**Comment by Neilblaze** [comment]
@sakshi1499 Before I create a PR, I want to review for the final time that the redirection to the correct wiki link is - https://github.com/anitab-org/portal/wiki

Also, there is a documentation mistake in the Systers Portal (https://github.com/anitab-org/portal) in "Setup-for-developers-windows" (https://github.com/anitab-org/portal#setup-for-developers-windows).

The correct method to create a virtual environment with Python 3 and install dependencies, using CMD (on Windows) would be -
```
$ virtualenv venv
$ .\venv\Scripts\activate
$ pip install -r requirements/dev.txt
```

instead of 
```
$ virtualenv venv
$ ./venv/Scripts/activate
$ pip install -r requirements/dev.txt
```

**Comment by sakshi1499** [comment]
@Neilblaze Yes. That is the correct link. For the changes in documentation, I think we have an issue for it already created. Ping about the changes you suggest there instead of mentioning it on this issue. ☺️

**Comment by Neilblaze** [comment]
Cool then 😃
Creating a PR!

**Comment by Neilblaze** [comment]
@sakshi1499 have a look!

**Comment by Neilblaze** [comment]
@sakshi1499 please check #577

**Comment by ritwickraj78** [comment]
@Neilblaze Approved
